### ISSUE TITLE
Functions of the Form

### ISSUE THREAD

**Issue by thermistor** [vanruby/talks#11]
## Functions of the Form

Several common patterns for using form objects in web applications, with a focus on Rails.

### Abstract

Form objects similar to service objects, policies, and query objects are one of the "missing" PORO components that don't come off-the-shelf in Rails. Here are some form object patterns I have used to make things simpler and more flexible in my projects.

### About the author

Weston Triemstra builds modern web applications at Netsign, a product development shop providing strategy, development and design. He and his team have a 🚢-load of experience creating and maintaining web applications for consumer and b2b businesses.

### Intended audience

This talk is for the Rails developer who wants to simplify their controllers or finds the Rails default paradigms insufficient.

### Length

6+ minutes (lightning talk), I can talk longer if need be.

**Comment by mctaylorpants** [comment]
Thanks for presenting!
