### ISSUE TITLE
Proponents of Components

### ISSUE THREAD

**Issue by thermistor** [vanruby/talks#12]
## Proponents of Components

[ViewComponents](https://viewcomponent.org/) are the new 🔥🔥🔥-ness, you need this.

### Abstract

Here are some tips discovered through using view components extensively over the last year.

### About the author

Weston Triemstra builds modern web applications at Netsign, a product development shop providing strategy, development and design. He and his team have a 🚢-load of experience creating and maintaining web applications for consumer and b2b businesses.

### Intended audience

This talk is for the Rails developer who wants to simplify their view layer or finds the Rails default paradigms insufficient.

### Length

6+ minutes (lightning talk), I can talk longer if need be.

**Comment by pcreux** [comment]
Hey @thermistor ! Do you want to give this talk at the next meetup?! (May 20)
