### ISSUE TITLE
Why I believe in Domain-Driven Design

### ISSUE THREAD

**Issue by vincent-truong** [vanruby/talks#14]
### Title
Why I believe in Domain-Driven Design

### Abstract
I've been studying the philosophy of Domain-Driven Design for a while and wanted to give a short talk on why I think it's empowering and what it could mean for people who practice it.

### About the author
I am Software Developer at Clio and love to learn.

### Intended audience
All levels.

### Length
2 minutes

**Comment by mctaylorpants** [comment]
Thanks for presenting!
