### ISSUE TITLE
Carbon-neutral Rails

### ISSUE THREAD

**Issue by thdaraujo** [vanruby/talks#15]
### Title

Do you want your app to have a low impact on the environment? 🌲 
I'll show you an easy way to make your app carbon-neutral and climate positive. 🌁 

### Abstract

We're building an API that let people purchase carbon offsets so they can make their applications carbon-neutral.
You can compensate carbon emissions related to shipping, flights, server usage... Pretty much anything.
I'll show you how to create a very simple integration with [Patch's API](https://github.com/patch-technology/patch-ruby).

### About the author

I'm a software engineer @ [Patch](https://www.patch.io/) and the co-host of the [hexdevs podcast](https://www.hexdevs.com/).

### Intended audience

all levels

### Length

6 minutes (lightning talk)

**Comment by mctaylorpants** [comment]
Thanks for presenting!
