### ISSUE TITLE
Service Objects using Dry-initializer, Dry-monads

### ISSUE THREAD

**Issue by scottbarrow** [vanruby/talks#16]
### Title

Keep it short and use emojis to make it stand out!

### Abstract

A quick talk about how we use Service Objects, Dry-initializer and Dry-monads at Ollie Order to shape our Service object and view component conventions

### About the author

Scott is the VP Engineering at Ollie Order and excited about finding clean abstractions for common high travel areas of the codebase. 

### Intended audience

Intermediate->Advanced

### Length
20 minutes, but can be distilled into 6 if needed

**Comment by mctaylorpants** [comment]
Hi, @scottbarrow, thanks for the submission! This sounds awesome, I love the dry suite.

We're doing lightning talks on March 11, so you're welcome to give a condensed version there, otherwise maybe we could feature the 20-minute version at a future meetup (maybe April). Let me know what you think.

**Comment by scottbarrow** [comment]
I don't think 6 minutes would do Monads justice with any useful context but maybe a latter meetup would be better

**Comment by mctaylorpants** [comment]
@scottbarrow agreed, I think this would be a great one for a fuller-length talk! Would you like to present this at April's meetup? We haven't set a date yet but it could be some time in mid-April, let me know if you're interested and what days might work best.
