### ISSUE TITLE
🤓 My Friend, the Database

### ISSUE THREAD

**Issue by timabdulla** [vanruby/talks#17]
### Title

🤓 My Friend, the Database

### Abstract

Relational databases are incredibly powerful, and yet we are often encouraged to treat the database as a black box, using it for only a tiny sliver of what it can do. Let's explore some of that power, and maybe end up making a new friend.

### About the author

👋 Hi, I'm Tim, the CTO at Rise People. Postgres gives me the butterflies. 🦋

### Intended audience

All levels

### Length

6 minutes (lightning talk)

**Comment by mctaylorpants** [comment]
Thanks for presenting!
