### ISSUE TITLE
Warp Speed with Postgres FDW (Foreign Data Wrapper) and Rails

### ISSUE THREAD

**Issue by cwangrise** [vanruby/talks#18]
### Title

Warp Speed with Postgres FDW (Foreign Data Wrapper) and Rails

### Abstract

We have encountered some performance issue on one of our services. It turns out that the problem is that it makes too many http calls to another service to get employee related information. And FDW can make it a lot faster. 

In this talk, I will talk about why and how we implement FDW, the prons and cons of the solution that I know of.

### About the author

Canvas Wang is a senior software engineer at Rise People (https://risepeople.com/).
Canvas enjoys solving problems, especially in Ruby. His linkedIn profile is https://www.linkedin.com/in/canvas-wang-847a652/.

### Intended audience

All levels

### Length

6 minutes (lightning talk)

**Comment by mctaylorpants** [comment]
Thanks for presenting!
