### ISSUE TITLE
Making sense of reams of data with Enumerable#slice_when

### ISSUE THREAD

**Issue by ericpromislow** [vanruby/talks#19]
### Title

Yet another way to cut a large amount of data to something manageable

### Abstract

If I write anything here it'll be longer than the talk.

### About the author

20 years now since a co-worker lent me his first edition pickaxe book, and Ruby is still my the language I use to have fun while getting things done.

### Intended audience

all levels

### Length

6 minutes (lightning talk) - more like 1 minute

**Comment by mctaylorpants** [comment]
Thanks for presenting!
