### ISSUE TITLE
The path to Staff Engineer

### ISSUE THREAD

**Issue by leonardofaria** [vanruby/talks#24]
### Title

The path to Staff Engineer

### Abstract

What happens after you reach a Senior Engineer position? Many go to the management roles, but which options do you have if you want to stay on a technical path? 

Sharing my thoughts based on my experience at Thinkific and the [Staff Engineer](https://staffeng.com) book

### About the author

technical architect at @thinkific, writes leonardofaria.net

### Intended audience

software engineers in general

### Length

20 minutes

**Comment by mctaylorpants** [comment]
@leonardofaria thanks for the submission! We're thinking of scheduling this for July 22nd at 1PM PT, would you be free? Since it's 20 minutes, we might see about having some lightning talks beforehand.

**Comment by leonardofaria** [comment]
Hi @mctaylorpants, July 22nd at 1 PM sounds good for me

**Comment by mctaylorpants** [comment]
@leonardofaria great! Looking forward to it. We'll announce the meetup in a few weeks.

**Comment by mctaylorpants** [comment]
@leonardofaria we just announced the meetup today: https://www.meetup.com/vancouver-ruby/events/279344837/

Looking forward to the talk!
