### ISSUE TITLE
mynatra: a simple and easy framework

### ISSUE THREAD

**Issue by christianarab** [vanruby/talks#26]
## Title
mynatra: a simple and easy framework
## Abstract
[mynatra](https://rubygems.org/gems/mynatra) is a Sinatra-based framework. Utilizing [Thor](https://github.com/erikhuda/thor) generators and ERB templates, it creates Ruby resource models with attributes, views, and controllers. 
mynatra can be used as the basis for small personal projects and tasks.
## About the author
I'm a newborn baby photographer, turn landscaper, turn wedding photo editor, turn dishwasher, turn line cook, turn waiter. 
But now, full-time student at [CompSci Academy](https://www.compsci.academy/)!
## Intended audience
Everyone.
## Length
6 minutes ⚡

**Comment by mctaylorpants** [comment]
@christianarab thanks for the submission! We'll probably be doing lightning talks again in late August (exact date TBD), would that work for you?

**Comment by christianarab** [comment]
@mctaylorpants Thanks for letting me know. A chance in late August sounds good. Will reconnect in the near future.

**Comment by mctaylorpants** [comment]
@christianarab on second thought, we could schedule this in for [next week's (July 22) meetup](https://www.meetup.com/vancouver-ruby/events/279344837/) - we're running a few lightning talks along with a longer talk. Would you be interested in presenting then?

**Comment by christianarab** [comment]
@mctaylorpants Hi, I appreciate this opportunity and would love to present! 👨🏽‍💻

**Comment by mctaylorpants** [comment]
@christianarab great, looking forward to it! You'll be up in the first ~20 minutes or so along with another talk, so join via the Zoom link in the meetup event at 1pm and we'll prompt you to share your screen when your time comes 🙂
