### ISSUE TITLE
Write your Ruby...while it's already running

### ISSUE THREAD

**Issue by rvirani1** [vanruby/talks#27]
_Note that while this talk is sort of funny and sarcastic to make it entertaining; it's not a fake submission. This is a real talk that I can actually give!_

### Title

Write your Ruby...while it's already running

### Abstract

Do you write your code in an editor and THEN run it? That's two whole steps! What if you could write your code while it was running? That's one step and we all know that one is better than two. Come to this session and we'll learn that you can actually write your Ruby from the inside out using the debugging gem, `pry`. We'll start with an empty program. Then we'll run it, write it, debug it, and commit it all without ever having to leave the terminal where the program is running. If you live for the thrill of programming that is both ambitious and completely unnecessary, then you'll love this talk.

### About the author

Riaz Virani has been building software since 2010. Currently, he works for his humble self on a stealth startup in the personal fitness space. Perviously, Riaz was the CTO at LoadUp Technologies in Atlanta. While Ruby is his original love, the exciting developments in JavaScript always beckon his curiosity. Riaz is also an avid movie and history buff. You can read more of his musings at riazv.me.

### Intended audience

all levels

### Length

Lightning Talk or 20 Minute Talk

**Comment by mctaylorpants** [comment]
Hey @rvirani1, this sounds like an awesome talk, thanks for the submission!

Our next round of lightning talks will be on August 19th at 1pm PT, would that time work for you?

**Comment by rvirani1** [comment]
Yup, works for me!

**Comment by pauloancheta** [comment]
This sounds so interesting!!!
