### ISSUE TITLE
Device Paring with security in mind

### ISSUE THREAD

**Issue by borisreitman** [vanruby/talks#3]
### Title

WhatsApp QR-code in Ruby-on-Rails

### Abstract

How to implement QR-code pairing, like WhatsApp does.

### About the author

I focus on Internet Security, and I run a meetup in Vancouver on this subject.  My background is Web Development, and I have worked with Ruby-on-Rails for a short time.  Homepage: borisreitman.com

### Intended audience

All levels.

### Length

I will adapt the content to the length. The longer, the better.  With longer time, I will have more time to go into encryption theory, as well as defences against "social engineering".

**Comment by mctaylorpants** [comment]
Hey @borisreitman, thanks for the submission!

I think this would work well as a lightning talk, since it could be useful to Ruby devs but not necessarily strongly focused on Ruby/Rails. What do you think? (We're doing lightning talks on the 14th if you're free).

**Comment by borisreitman** [comment]
I will do it. I have RSVPed on the meetup, and marked my calendar.

**Comment by mctaylorpants** [comment]
Awesome! See you then.

>
