### ISSUE TITLE
November VanRuby Talk Submission

### ISSUE THREAD

**Issue by andwaller** [vanruby/talks#30]
### Title
**How we made our Ruby App Concurrent Golang Style!** 

Keep it short and use emojis to make it stand out!

### Abstract

**Concurrency is one GoLang’s most prominent features. So when our Ruby Library was crashing randomly, how did we use Concurrency in our Ruby application?

What happened when they added more code to fix the crashes?

What was the refactoring process?

How did they test such a significant change?

In this talk, Sudhindra will share the process his team took to work through this issue, and how they incorporated Asynchronous Processing while leveraging Golang style concurrency in a Ruby application. He will also showcase concepts of using Concurrency mechanisms in Ruby.**

### About the author

**Sudhindra Rao currently works at JFrog as Development Manager to help build communities and partnerships to provide visibility into JFrog’s liquid software mission. He has been working as a developer/architect for critical business applications developing in multiple languages including, Go, Ruby, and Java. After having worked in traditional application development, Sudhindra became part of the Pivotal team and built their Kubernetes(k8s) platform offering. Sudhindra’s diverse project experiences include: building an application for the largest publishing company in Chicago, a large data center automation effort, a large auctioning system, and a voter campaigning application for US national elections**

### Intended audience

beginners, intermediates, advanced, all levels? All Levels

### Length

**45 minutes**

**Comment by andwaller** [comment]
Thanks @pauloancheta - I spoke with Sudhindra and he will be happy to give a talk on Nov 19.  Do you have all the details you need from me for the Meetup Page?  Also - what time does the event begin?

Ari

**Comment by andwaller** [comment]
@pauloancheta we are confirmed. Will you send me an email address for you and/or the Vanruby?

**Comment by pauloancheta** [comment]
Hey @andwaller, I've just announced the meetup on November 18 :)
