### ISSUE TITLE
[Talk Proposal] Enough Coverage To Beat The Band

### ISSUE THREAD

**Issue by kevin-j-m** [vanruby/talks#32]
### Title

Enough Coverage To Beat The Band

### Abstract

The lights cut out. The crowd roars. It’s time. The band takes the stage. They’ve practiced the songs, particularly the covers. They’ve sound checked the coverage of the speakers. They know the lighting rig has the proper colored gels covering the lamps. They’re nervous, but they’ve got it all covered.

Similarly, code coverage can give you confidence before your app performs on production and also tell you how live code is used (or not used). We’ll cover how to leverage ruby’s different coverage measurement techniques in concert to assist your crew and delight your audience.

### About the author

[Kevin](https://kevinjmurphy.com/) lives near Boston, MA, US, where he is a Software Developer. He’s doing the best he can to cope with 2 years of concerts that could have been.

[Twitter](https://twitter.com/kevin_j_m)

### Intended audience

All levels

### Length

45 minutes (should be about 30 minutes + questions)

**Comment by kevin-j-m** [comment]
Feb 24 can work for me. Would you be keeping your 1pm (local time) schedule you've had recently? That'd work great for me (I'm on the East Coast US).

**Comment by pauloancheta** [comment]
Yeah, it would be at 1pm 👍

**Comment by kevin-j-m** [comment]
That sounds great. What else do you need from me to help move this forward?

**Comment by pauloancheta** [comment]
I've just announced the meetup on twitter and on Vancouver Developers ruby slack group. The meetup event is also live https://www.meetup.com/vancouver-ruby/events/283653291/
