### ISSUE TITLE
Going Fast

### ISSUE THREAD

**Issue by lcowell** [vanruby/talks#33]
### Title

Going Fast

### Abstract

A short story about going fast in a startup and a lesson learned.

### About the author

Luke  is the CoFounder of a couple of successful startups, and is exploring ways to give back to the community.

https://www.linkedin.com/in/lukebcowell/

### Intended audience

All levels

### Length

4-5 minutes

**Comment by lcowell** [comment]
This would be a great little nugget for today's lightening talks.

**Comment by mctaylorpants** [comment]
Hurray! 🎉 Thanks Luke, looking forward to it.
