### ISSUE TITLE
How I learned to develop software like a bureaucrat

### ISSUE THREAD

**Issue by alexbunardzic** [vanruby/talks#36]
### Abstract

Even moderately complex software systems tend to be notoriously brittle. What usually causes the brittleness are dependencies. Parts of the system depend on some other parts of the system, which in turn depend on some other parts, and so on. Such dependencies tend to harden into tightly coupled brittle surfaces. As soon as we start applying the pressures of unavoidable changes, the brittle surface begins to crack. More often than not, such cracks quickly turn into serious breakages. How to address this ever present issue? We’ve tried many different approaches, but somehow entropy always gets its way, and we end up crossing our fingers and hoping for the best while expecting the worst. In my experience, the best approach to attempt to tame such accidental complexities is to mirror and adopt the way large organizations have implemented complex systems. The tried and tested method, that has been in use for many generations, is the system we call bureaucracy. Obviously, bureaucracies work without constantly breaking down. They may not be the most efficient or the most effective systems, but overall the batting average of a typical bureaucratic system outperforms many/most software systems that are in production today. This talk will focus on how to transform the software development process so that the delivered system is less brittle, more resilient, more open for unforeseen changes that the future inevitably brings.

### About the author

Alex Bunardzic is a software development professional known for his innovative approach to technology and digital solutions. With a career spanning several decades, Alex has established himself as a respected figure in the tech industry, especially in the area of software development. He possesses a deep understanding of various development methodologies, making him proficient in creating robust and efficient software solutions. Alex's dedication to his field is evident in his continuous pursuit of knowledge and his enthusiasm for embracing new technologies. Outside of his professional pursuits, Alex is passionate about music, particularly playing the guitar. He also has a keen interest in high-quality audio experiences and enjoys collecting vinyl records. This combination of technical expertise and artistic inclination makes Alex a unique and multifaceted individual in the tech world.

Email: [alexbunardzic@gmail.com](mailto:alexbunardzic@gmail.com)
Medium: https://medium.com/@alexbunardzic
Twitter: https://x.com/alexbunardzic
LinkedIn: https://www.linkedin.com/in/alexbunardzic/
Substack: https://substack.com/@alexbunardzic
Coding interviews with Alex https://www.youtube.com/playlist?list=PLpQwCufTgsb21EuS262M1dn1dhgqInndD
Software breakthroughs for the 21st century
https://www.youtube.com/playlist?list=PLpQwCufTgsb2z_FW8FFbOzr7uBU-kuydQ
Diary of a perplexed software developer
https://www.youtube.com/playlist?list=PLpQwCufTgsb1jE8l6JuxkHAJnAbLzb46v

### Intended audience

All levels

### Length

45 minutes

**Comment by thermistor** [comment]
Talk given July 16, 2024 at BrainStation
