### ISSUE TITLE
Undervalued: The Most Useful Design Pattern

### ISSUE THREAD

**Issue by jarednorman** [vanruby/talks#38]
### Title

Undervalued: The Most Useful Design Pattern

### Abstract

Value objects are one of the most useful but underused object-oriented software design patterns. Now that Ruby has first class support for them, let’s explore what we can do with them! Learn not just how and when to use value objects, but also how they can be used to bridge different domains, make your tests faster and more maintainable, and even make your code more performant. I’ll even show how to combine value objects with the factory pattern to create the most useful design pattern out there.

### About the author

I'm Jared, but you can call me [Jardo](https://jardo.dev) if you want. I run a consultancy called [Super Good Software](https://supergood.software) where we help organizations learn from the past to build software more effectively. I think Ruby is a wonderful language and have been building cool stuff with it for around fifteen years. When I'm not coding you'll find me surfing. When I _am_ coding you'll find me listening to whatever new metal albums came out this week. 🤘

### Intended audience

There's something for all levels, but it targets intermediate developers.

### Length

45 minutes

**This talk was previously given at RailsConf 2024, but at the time of writing the videos aren't live yet, so the talk isn't currently available online.**

**Comment by thermistor** [comment]
Talk given on June 11, 2024 at BratinStation.
