### ISSUE TITLE
Internals of a permission system

### ISSUE THREAD

**Issue by nuvic** [vanruby/talks#39]
### Title

Internals of a permissions system

### Abstract

This is a dive into how you can implement a library like [Pundit](https://github.com/varvet/pundit) to help you build a simple and robust permissions system.

### About the author

I'm Newvick, and I've been programming with ruby in the last two companies I've worked at. It's a great language for developer productivity.

[website](https://newvick.com/)
[linkedin](https://www.linkedin.com/in/newvick-lee/)

### Intended audience

beginner to intermediate

### Length

15 mins

**Comment by thermistor** [comment]
Talk given June 11, 2024 at BrainStation.
