### ISSUE TITLE
Developing yourself as a Junior Developer

### ISSUE THREAD

**Issue by stefannibrasil** [vanruby/talks#5]
### Title

Developing yourself as a Junior Developer

### Abstract
Being a Junior Developer means that you have not only how to learn more complex stuff, but you also need to learn good practices, tests, and many other skills like clean code and working on a team. But, fear not, because you're not alone! On this talk, I'm going to talk about the lessons that I've been learning for the past months and hopefully have some practical advice for those who are in the same boat, especially for those who love Ruby!

### About the author

Junior Software Developer, with a passion for UX. Cat lover,  likes to write on her [Blog](http://stefannibrasil.me/).

### Intended audience

Juniors, Beginners

### Length

6 minutes

**Comment by pauloancheta** [comment]
Hey @stefannibrasil would you be ready to present for March 14?

**Comment by stefannibrasil** [comment]
hi @pauloancheta yes, I am :)

**Comment by pauloancheta** [comment]
Awesome! See you on the 14th!

**Comment by stefannibrasil** [comment]
Can I present the other talk about System Tests as well?

**Comment by pauloancheta** [comment]
Let's try to limit 1 person per talk for now. If there are no other presenters, then we'll include that.
