### ISSUE TITLE
Defending from URL-based Attacks

### ISSUE THREAD

**Issue by borisreitman** [vanruby/talks#9]
### Title

Defending from URL-based Attacks

### Abstract

Many hacking attacks begin with a URL.  How can you detect malicious URL submissions in your code?

### About the author

I am a web developer, and I run a local meetup focused on security and privacy.

### Intended audience

All levels.

### Length

Lightning talk

**Comment by pcreux** [comment]
@borisreitman We're running lightning talks on October 3. Do you want to give this one?

https://www.meetup.com/vancouver-ruby/events/264794698/

**Comment by borisreitman** [comment]
@pcreux I'm out of town that day. When would be the event after that?

**Comment by pcreux** [comment]
Not sure when the next Lightning Talks event will be. Maybe early next year?

φ
